[package]
name = "blue"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
ledbetter = { path = "../.." }
palette = "0.6.0"
wee_alloc = "0.4.5"

[profile.release]
lto = true
